snapshot of project "copyrite", label t20221231

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 # From configure.in Revision: 5.6 .
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20221009.
+# Generated by Autoconf 2.52.20221202.
 #
 # Copyright 2003-2021,2022	Thomas E. Dickey
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -728,7 +728,7 @@ This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
 It was created by $as_me, which was
-generated by GNU Autoconf 2.52.20221009.  Invocation command line was
+generated by GNU Autoconf 2.52.20221202.  Invocation command line was
 
   $ $0 $@
 
@@ -3192,12 +3192,15 @@ done
 			fi
 		done
 	else
-		cf_libdir=`echo "$cf_libdir" | sed -e 's,/lib[^/]*$,share,'`
+		cf_libdir=`echo "$cf_libdir" | sed -e 's,/td_lib.mk,,' -e 's,/lib[^/]*,/share,'`
 		if test -f "$cf_libdir/td_lib.mk" ; then
+			cf_td_lib_rules=yes
+		elif test -f "$cf_libdir/td/td_lib.mk" ; then
+			cf_libdir="$cf_libdir/td"
 			cf_td_lib_rules=yes
 		fi
 	fi
-	test $cf_td_lib_rules = no && { { echo "$as_me:3200: error: Cannot find td_lib.mk" >&5
+	test "$cf_td_lib_rules" = yes || { { echo "$as_me:3203: error: Cannot find td_lib.mk" >&5
 echo "$as_me: error: Cannot find td_lib.mk" >&2;}
    { (exit 1); exit 1; }; }
 	TD_LIB_rules=$cf_libdir
@@ -3207,7 +3210,7 @@ else
 	TD_LIB_rules=$cf_cv_tdlib_devel/support
 fi
 
-echo "$as_me:3210: checking for style of include in makefiles" >&5
+echo "$as_me:3213: checking for style of include in makefiles" >&5
 echo $ECHO_N "checking for style of include in makefiles... $ECHO_C" >&6
 
 make_include_left=""
@@ -3247,7 +3250,7 @@ done
 rm -rf $cf_inc $cf_dir
 
 if test -z "$make_include_left" ; then
-	{ { echo "$as_me:3250: error: Your $ac_make program does not support includes" >&5
+	{ { echo "$as_me:3253: error: Your $ac_make program does not support includes" >&5
 echo "$as_me: error: Your $ac_make program does not support includes" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3256,11 +3259,11 @@ if test ".$make_include_quote" != .unknown ; then
 	make_include_right="$make_include_quote"
 fi
 
-echo "$as_me:3259: result: ${make_include_left}file${make_include_right}" >&5
+echo "$as_me:3262: result: ${make_include_left}file${make_include_right}" >&5
 echo "${ECHO_T}${make_include_left}file${make_include_right}" >&6
 
 ###	use option -with-warnings to turn on all gcc warnings
-echo "$as_me:3263: checking for fgrep" >&5
+echo "$as_me:3266: checking for fgrep" >&5
 echo $ECHO_N "checking for fgrep... $ECHO_C" >&6
 if test "${ac_cv_path_FGREP+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3272,7 +3275,7 @@ else
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:3275: checking for $ac_word" >&5
+echo "$as_me:3278: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_FGREP+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3289,7 +3292,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_FGREP="$ac_dir/$ac_word"
-   echo "$as_me:3292: found $ac_dir/$ac_word" >&5
+   echo "$as_me:3295: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -3300,10 +3303,10 @@ fi
 FGREP=$ac_cv_path_FGREP
 
 if test -n "$FGREP"; then
-  echo "$as_me:3303: result: $FGREP" >&5
+  echo "$as_me:3306: result: $FGREP" >&5
 echo "${ECHO_T}$FGREP" >&6
 else
-  echo "$as_me:3306: result: no" >&5
+  echo "$as_me:3309: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3311,16 +3314,16 @@ fi
 done
 test -n "$FGREP" || FGREP=": "
 
-     test "x$ac_cv_path_FGREP" = "x:" && { { echo "$as_me:3314: error: cannot find workable fgrep" >&5
+     test "x$ac_cv_path_FGREP" = "x:" && { { echo "$as_me:3317: error: cannot find workable fgrep" >&5
 echo "$as_me: error: cannot find workable fgrep" >&2;}
    { (exit 1); exit 1; }; }
    fi
 fi
-echo "$as_me:3319: result: $ac_cv_path_FGREP" >&5
+echo "$as_me:3322: result: $ac_cv_path_FGREP" >&5
 echo "${ECHO_T}$ac_cv_path_FGREP" >&6
  FGREP="$ac_cv_path_FGREP"
 
-echo "$as_me:3323: checking if you want to use C11 _Noreturn feature" >&5
+echo "$as_me:3326: checking if you want to use C11 _Noreturn feature" >&5
 echo $ECHO_N "checking if you want to use C11 _Noreturn feature... $ECHO_C" >&6
 
 # Check whether --enable-stdnoreturn or --disable-stdnoreturn was given.
@@ -3337,17 +3340,17 @@ else
 	enable_stdnoreturn=no
 
 fi;
-echo "$as_me:3340: result: $enable_stdnoreturn" >&5
+echo "$as_me:3343: result: $enable_stdnoreturn" >&5
 echo "${ECHO_T}$enable_stdnoreturn" >&6
 
 if test $enable_stdnoreturn = yes; then
-echo "$as_me:3344: checking for C11 _Noreturn feature" >&5
+echo "$as_me:3347: checking for C11 _Noreturn feature" >&5
 echo $ECHO_N "checking for C11 _Noreturn feature... $ECHO_C" >&6
 if test "${cf_cv_c11_noreturn+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >"conftest.$ac_ext" <<_ACEOF
-#line 3350 "configure"
+#line 3353 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -3364,16 +3367,16 @@ if (feof(stdin)) giveup()
 }
 _ACEOF
 rm -f "conftest.$ac_objext"
-if { (eval echo "$as_me:3367: \"$ac_compile\"") >&5
+if { (eval echo "$as_me:3370: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3370: \$? = $ac_status" >&5
+  echo "$as_me:3373: \$? = $ac_status" >&5
   (exit "$ac_status"); } &&
          { ac_try='test -s "conftest.$ac_objext"'
-  { (eval echo "$as_me:3373: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3376: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3376: \$? = $ac_status" >&5
+  echo "$as_me:3379: \$? = $ac_status" >&5
   (exit "$ac_status"); }; }; then
   cf_cv_c11_noreturn=yes
 else
@@ -3384,7 +3387,7 @@ fi
 rm -f "conftest.$ac_objext" "conftest.$ac_ext"
 
 fi
-echo "$as_me:3387: result: $cf_cv_c11_noreturn" >&5
+echo "$as_me:3390: result: $cf_cv_c11_noreturn" >&5
 echo "${ECHO_T}$cf_cv_c11_noreturn" >&6
 else
 	cf_cv_c11_noreturn=no,
@@ -3440,16 +3443,16 @@ then
 		then
 			test -n "$verbose" && echo "	repairing CFLAGS: $CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3443: testing repairing CFLAGS: $CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3446: testing repairing CFLAGS: $CFLAGS ..." 1>&5
 
 			CFLAGS="$cf_temp_flags"
 			test -n "$verbose" && echo "	... fixed $CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3448: testing ... fixed $CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3451: testing ... fixed $CFLAGS ..." 1>&5
 
 			test -n "$verbose" && echo "	... extra $EXTRA_CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3452: testing ... extra $EXTRA_CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3455: testing ... extra $EXTRA_CFLAGS ..." 1>&5
 
 		fi
 		;;
@@ -3488,16 +3491,16 @@ then
 		then
 			test -n "$verbose" && echo "	repairing CPPFLAGS: $CPPFLAGS" 1>&6
 
-echo "${as_me:-configure}:3491: testing repairing CPPFLAGS: $CPPFLAGS ..." 1>&5
+echo "${as_me:-configure}:3494: testing repairing CPPFLAGS: $CPPFLAGS ..." 1>&5
 
 			CPPFLAGS="$cf_temp_flags"
 			test -n "$verbose" && echo "	... fixed $CPPFLAGS" 1>&6
 
-echo "${as_me:-configure}:3496: testing ... fixed $CPPFLAGS ..." 1>&5
+echo "${as_me:-configure}:3499: testing ... fixed $CPPFLAGS ..." 1>&5
 
 			test -n "$verbose" && echo "	... extra $EXTRA_CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3500: testing ... extra $EXTRA_CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3503: testing ... extra $EXTRA_CFLAGS ..." 1>&5
 
 		fi
 		;;
@@ -3536,23 +3539,23 @@ then
 		then
 			test -n "$verbose" && echo "	repairing LDFLAGS: $LDFLAGS" 1>&6
 
-echo "${as_me:-configure}:3539: testing repairing LDFLAGS: $LDFLAGS ..." 1>&5
+echo "${as_me:-configure}:3542: testing repairing LDFLAGS: $LDFLAGS ..." 1>&5
 
 			LDFLAGS="$cf_temp_flags"
 			test -n "$verbose" && echo "	... fixed $LDFLAGS" 1>&6
 
-echo "${as_me:-configure}:3544: testing ... fixed $LDFLAGS ..." 1>&5
+echo "${as_me:-configure}:3547: testing ... fixed $LDFLAGS ..." 1>&5
 
 			test -n "$verbose" && echo "	... extra $EXTRA_CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3548: testing ... extra $EXTRA_CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3551: testing ... extra $EXTRA_CFLAGS ..." 1>&5
 
 		fi
 		;;
 	esac
 fi
 
-echo "$as_me:3555: checking if you want to turn on gcc warnings" >&5
+echo "$as_me:3558: checking if you want to turn on gcc warnings" >&5
 echo $ECHO_N "checking if you want to turn on gcc warnings... $ECHO_C" >&6
 
 # Check whether --enable-warnings or --disable-warnings was given.
@@ -3569,7 +3572,7 @@ else
 	enable_warnings=no
 
 fi;
-echo "$as_me:3572: result: $enable_warnings" >&5
+echo "$as_me:3575: result: $enable_warnings" >&5
 echo "${ECHO_T}$enable_warnings" >&6
 if test "$enable_warnings" = "yes"
 then
@@ -3592,10 +3595,11 @@ cat > conftest.i <<EOF
 EOF
 if test "$GCC" = yes
 then
-	{ echo "$as_me:3595: checking for $CC __attribute__ directives..." >&5
+	{ echo "$as_me:3598: checking for $CC __attribute__ directives..." >&5
 echo "$as_me: checking for $CC __attribute__ directives..." >&6;}
 cat > "conftest.$ac_ext" <<EOF
-#line 3598 "${as_me:-configure}"
+#line 3601 "${as_me:-configure}"
+#include <stdio.h>
 #include "confdefs.h"
 #include "conftest.h"
 #include "conftest.i"
@@ -3644,12 +3648,12 @@ EOF
 			;;
 		esac
 
-		if { (eval echo "$as_me:3647: \"$ac_compile\"") >&5
+		if { (eval echo "$as_me:3651: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3650: \$? = $ac_status" >&5
+  echo "$as_me:3654: \$? = $ac_status" >&5
   (exit "$ac_status"); }; then
-			test -n "$verbose" && echo "$as_me:3652: result: ... $cf_attribute" >&5
+			test -n "$verbose" && echo "$as_me:3656: result: ... $cf_attribute" >&5
 echo "${ECHO_T}... $cf_attribute" >&6
 			cat conftest.h >>confdefs.h
 			case "$cf_attribute" in
@@ -3710,7 +3714,7 @@ fi
 
 if test "x$have_x" = xyes; then echo "skipping X-const check"; fi
 cat > "conftest.$ac_ext" <<EOF
-#line 3713 "${as_me:-configure}"
+#line 3717 "${as_me:-configure}"
 int main(int argc, char *argv[]) { return (argv[argc-1] == 0) ; }
 EOF
 if test "$INTEL_COMPILER" = yes
@@ -3726,7 +3730,7 @@ then
 # remark #981: operands are evaluated in unspecified order
 # warning #279: controlling expression is constant
 
-	{ echo "$as_me:3729: checking for $CC warning options..." >&5
+	{ echo "$as_me:3733: checking for $CC warning options..." >&5
 echo "$as_me: checking for $CC warning options..." >&6;}
 	cf_save_CFLAGS="$CFLAGS"
 	EXTRA_CFLAGS="$EXTRA_CFLAGS -Wall"
@@ -3742,12 +3746,12 @@ echo "$as_me: checking for $CC warning options..." >&6;}
 		wd981
 	do
 		CFLAGS="$cf_save_CFLAGS $EXTRA_CFLAGS -$cf_opt"
-		if { (eval echo "$as_me:3745: \"$ac_compile\"") >&5
+		if { (eval echo "$as_me:3749: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3748: \$? = $ac_status" >&5
+  echo "$as_me:3752: \$? = $ac_status" >&5
   (exit "$ac_status"); }; then
-			test -n "$verbose" && echo "$as_me:3750: result: ... -$cf_opt" >&5
+			test -n "$verbose" && echo "$as_me:3754: result: ... -$cf_opt" >&5
 echo "${ECHO_T}... -$cf_opt" >&6
 			EXTRA_CFLAGS="$EXTRA_CFLAGS -$cf_opt"
 		fi
@@ -3755,7 +3759,7 @@ echo "${ECHO_T}... -$cf_opt" >&6
 	CFLAGS="$cf_save_CFLAGS"
 elif test "$GCC" = yes && test "$GCC_VERSION" != "unknown"
 then
-	{ echo "$as_me:3758: checking for $CC warning options..." >&5
+	{ echo "$as_me:3762: checking for $CC warning options..." >&5
 echo "$as_me: checking for $CC warning options..." >&6;}
 	cf_save_CFLAGS="$CFLAGS"
 	cf_warn_CONST=""
@@ -3778,12 +3782,12 @@ echo "$as_me: checking for $CC warning options..." >&6;}
 		Wundef Wno-inline $cf_gcc_warnings $cf_warn_CONST
 	do
 		CFLAGS="$cf_save_CFLAGS $EXTRA_CFLAGS -$cf_opt"
-		if { (eval echo "$as_me:3781: \"$ac_compile\"") >&5
+		if { (eval echo "$as_me:3785: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3784: \$? = $ac_status" >&5
+  echo "$as_me:3788: \$? = $ac_status" >&5
   (exit "$ac_status"); }; then
-			test -n "$verbose" && echo "$as_me:3786: result: ... -$cf_opt" >&5
+			test -n "$verbose" && echo "$as_me:3790: result: ... -$cf_opt" >&5
 echo "${ECHO_T}... -$cf_opt" >&6
 			case "$cf_opt" in
 			(Winline)
@@ -3791,7 +3795,7 @@ echo "${ECHO_T}... -$cf_opt" >&6
 				([34].*)
 					test -n "$verbose" && echo "	feature is broken in gcc $GCC_VERSION" 1>&6
 
-echo "${as_me:-configure}:3794: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
+echo "${as_me:-configure}:3798: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
 
 					continue;;
 				esac
@@ -3801,7 +3805,7 @@ echo "${as_me:-configure}:3794: testing feature is broken in gcc $GCC_VERSION ..
 				([12].*)
 					test -n "$verbose" && echo "	feature is broken in gcc $GCC_VERSION" 1>&6
 
-echo "${as_me:-configure}:3804: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
+echo "${as_me:-configure}:3808: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
 
 					continue;;
 				esac
@@ -3939,7 +3943,7 @@ rm -f confdef2opt.sed
 : "${CONFIG_STATUS=./config.status}"
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3942: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3946: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >"$CONFIG_STATUS" <<_ACEOF
 #! $SHELL
@@ -4070,7 +4074,7 @@ EOF
 cat >>"$CONFIG_STATUS" <<EOF
 ac_cs_version="\\
 config.status
-configured by $0, generated by GNU Autoconf 2.52.20221009,
+configured by $0, generated by GNU Autoconf 2.52.20221202,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 2003-2021,2022	Thomas E. Dickey
@@ -4115,7 +4119,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4118: error: ambiguous option: $1
+    { { echo "$as_me:4122: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4134,7 +4138,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4137: error: unrecognized option: $1
+  -*) { { echo "$as_me:4141: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4153,7 +4157,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me 2.52.20221009, executed with
+This file was extended by $as_me 2.52.20221202, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -4185,7 +4189,7 @@ do
   "test/makefile" ) CONFIG_FILES="$CONFIG_FILES test/makefile" ;;
   "user/makefile" ) CONFIG_FILES="$CONFIG_FILES user/makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
-  *) { { echo "$as_me:4188: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4192: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4439,7 +4443,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4442: creating $ac_file" >&5
+    { echo "$as_me:4446: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4457,7 +4461,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4460: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4464: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo "$f";;
@@ -4470,7 +4474,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:4473: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4477: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4486,7 +4490,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' "$ac_item"`
         if test -z "$ac_used"; then
-          { echo "$as_me:4489: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:4493: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -4495,7 +4499,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' "$ac_item"`
       if test -n "$ac_seen"; then
-        { echo "$as_me:4498: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:4502: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -4540,7 +4544,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
             ac_init=`$EGREP '[ 	]*'$ac_name'[ 	]*=' "$ac_file"`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'"$ac_file"':,'`
-              { echo "$as_me:4543: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:4547: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -4551,7 +4555,7 @@ $ac_seen" >&2;}
     $EGREP -n '@[A-Z_][A-Z_0-9]+@' "$ac_file" >>"$tmp"/out
     if test -s "$tmp"/out; then
       ac_seen=`sed -e 's,^,'"$ac_file"':,' < "$tmp"/out`
-      { echo "$as_me:4554: WARNING: Some variables may not be substituted:
+      { echo "$as_me:4558: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
